import { Document, Page, Text, View, StyleSheet, Font, Image, Link } from '@react-pdf/renderer';
import QRCode from 'qrcode';

// Register Fonts (Kanit & Sarabun)
// Note: In a real app, you need to register fonts from a URL or local path.
// For this demo, we'll try to use standard fonts or assume font registration happens elsewhere.
Font.register({
    family: 'Sarabun',
    fonts: [
        { src: 'https://fonts.gstatic.com/s/sarabun/v13/DtVjJx26TKEr37c9aAFJn2QN.woff2' }, // Regular
        { src: 'https://fonts.gstatic.com/s/sarabun/v13/DtVkJx26TKEr37c9aAFo.woff2', fontWeight: 'bold' },
    ]
});

const styles = StyleSheet.create({
    page: {
        padding: 40,
        fontFamily: 'Sarabun',
        fontSize: 12,
        lineHeight: 1.5,
    },
    coverPage: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        height: '100%',
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 20,
        textAlign: 'center',
    },
    subtitle: {
        fontSize: 16,
        marginBottom: 10,
        textAlign: 'center',
        color: '#4b5563',
    },
    toc: {
        marginTop: 40,
    },
    tocItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 5,
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
        borderBottomStyle: 'dotted',
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        marginTop: 20,
        marginBottom: 10,
        backgroundColor: '#f3f4f6',
        padding: 5,
    },
    content: {
        marginBottom: 10,
        textAlign: 'justify',
    },
    evidenceRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 5,
        marginBottom: 5,
        padding: 5,
        borderWidth: 1,
        borderColor: '#e0e7ff',
        borderRadius: 4,
        backgroundColor: '#eef2ff',
    },
    qrCode: {
        width: 40,
        height: 40,
        marginRight: 10,
    },
    evidenceLink: {
        color: '#4f46e5',
        textDecoration: 'none',
        fontSize: 10,
    },
    pageNumber: {
        position: 'absolute',
        fontSize: 10,
        bottom: 20,
        left: 0,
        right: 0,
        textAlign: 'center',
        color: '#9ca3af',
    },
});

interface SARData {
    cycleName: string;
    unitName: string;
    sections: {
        id: string; // e.g., "1.1"
        title: string;
        content: string;
        evidences: {
            name: string;
            url: string;
        }[];
    }[];
}

// Generate QR Code Data URL
const generateQR = async (url: string) => {
    try {
        return await QRCode.toDataURL(url);
    } catch (err) {
        console.error(err);
        return '';
    }
};

export const SAREbookDocument = ({ data, qrCodes }: { data: SARData, qrCodes: Record<string, string> }) => (
    <Document>
        {/* Cover Page */}
        <Page size="A4" style={styles.page}>
            <View style={styles.coverPage}>
                <Image src="/images/isoc-logo.png" style={{ width: 100, height: 100, marginBottom: 20 }} />
                <Text style={styles.title}>รายงานการประเมินตนเอง (SAR)</Text>
                <Text style={styles.title}>PMQA 4.0</Text>
                <Text style={styles.subtitle}>{data.unitName}</Text>
                <Text style={styles.subtitle}>{data.cycleName}</Text>
                <Text style={{ marginTop: 50, fontSize: 10, color: '#6b7280' }}>
                    Generated by Smart PMQA System
                </Text>
            </View>
        </Page>

        {/* Table of Content */}
        <Page size="A4" style={styles.page}>
            <Text style={styles.title}>สารบัญ</Text>
            <View style={styles.toc}>
                {data.sections.map((section) => (
                    <Link key={section.id} src={`#${section.id}`} style={{ textDecoration: 'none', color: 'black' }}>
                        <View style={styles.tocItem}>
                            <Text>{section.title}</Text>
                        </View>
                    </Link>
                ))}
            </View>
        </Page>

        {/* Content Pages */}
        <Page size="A4" style={styles.page}>
            {data.sections.map((section) => (
                <View key={section.id} id={section.id} break={section.id.endsWith('.1')}>
                    <Text style={styles.sectionTitle}>{section.title}</Text>
                    <Text style={styles.content}>{section.content}</Text>

                    {/* Evidence Links with QR Codes */}
                    {section.evidences.length > 0 && (
                        <View style={{ marginTop: 10 }}>
                            <Text style={{ fontSize: 10, fontWeight: 'bold', marginBottom: 5 }}>หลักฐานประกอบ:</Text>
                            {section.evidences.map((ev, idx) => (
                                <View key={idx} style={styles.evidenceRow}>
                                    {qrCodes[ev.url] && (
                                        <Image src={qrCodes[ev.url]} style={styles.qrCode} />
                                    )}
                                    <View>
                                        <Text style={{ fontSize: 10, fontWeight: 'bold' }}>{ev.name}</Text>
                                        <Link src={ev.url} style={styles.evidenceLink}>
                                            {ev.url}
                                        </Link>
                                    </View>
                                </View>
                            ))}
                        </View>
                    )}
                </View>
            ))}
            <Text style={styles.pageNumber} render={({ pageNumber, totalPages }) => (
                `${pageNumber} / ${totalPages}`
            )} fixed />
        </Page>
    </Document>
);
